src/Entity/Figure.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FigureRepository")
 * @UniqueEntity(fields={"name"})
 */
class Figure
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return Figure
     */
    public function setSlug(string $slug)
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FiguresGroup", inversedBy="figures", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $figuresGroup;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="figure", cascade={"all"}, fetch="EAGER", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="figure", cascade={"all"}, fetch="EAGER", orphanRemoval=true)
     */
    private $links;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="figure",  cascade={"all"}, fetch="EAGER", orphanRemoval=true)
     */
    private $comments;


    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTime();
        $this->images = new ArrayCollection();
        $this->links = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Link[]
     */
    public function getLinks() : Collection
    {
        return $this->links;
    }

    /**
     * @param Collection $link
     */
    public function setLinks(Collection $link): void
    {
        $this->$link = $link;
    }

    public function addLink(Link $link) : self
    {
        if (!$this->links->contains($link)) {
            $this->links[] = $link;
            $link->setFigure($this);
        }

        return $this;
    }

    public function removeLink(Link $link) : self
    {
        if ($this->links->contains($link)) {
            $this->links->removeElement($link);
            // set the owning side to null (unless already changed)
            if ($link->getFigure() === $this) {
                $link->setFigure(null);
            }
        }

        return $this;
    }

    public function getFiguresGroup(): ?FiguresGroup
    {
        return $this->figuresGroup;
    }

    public function setFiguresGroup(?FiguresGroup $figuresGroup): self
    {
        $this->figuresGroup = $figuresGroup;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    /**
     * @param Collection $image
     */
    public function setImages(Collection $image): void
    {
        $this->$image = $image;
    }


    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setFigure($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getFigure() === $this) {
                $image->setFigure(null);
            }
        }

        return $this;
    }

    public function getFirstImage() : string
    {
        return $this->getImages()->first()->getImagePath();
    }

    public function getFirstImageId() : int
    {
        return $this->getImages()->first()->getId();
    }

    public function countImages() : int
    {
        return $this->getImages()->count();
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setFigure($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getFigure() === $this) {
                $comment->setFigure(null);
            }
        }

        return $this;
    }
}

src/Controller/Logged/FigureController.php
<?php

namespace App\Controller\Logged;

use App\Entity\Figure;
use App\Entity\Image;
use App\Form\FigureType;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class FigureController extends AbstractController
{
    private $filesTargetDirectory;
    private $entityManager;

    public function __construct(string $filesTargetDirectory, EntityManagerInterface $entityManager)
    {
        $this->filesTargetDirectory = $filesTargetDirectory;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/logged/create", name="create_figure")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @return Response
     */
    public function createFigure(Request $request, ValidatorInterface $validator)
    {
        $figure = new Figure();

        $form = $this->createForm(FigureType::class, $figure);
        $form->handleRequest($request);

        $success = false;

        if($request->isMethod('POST') && $form->isSubmitted()) {
            if($form->isValid()) {
                $success = true;
                $session = $this->container->get('session');
                $session->getFlashBag()->set('success', 'Your Trick has been successfully created !');

                $this->entityManager->persist($figure);
                $this->entityManager->flush();

                return $this->redirectToRoute('create_figure', [
                    'success' => $success
                ]);
            } else {
                foreach ($figure->getImages() as $image) {
                    unlink($this->filesTargetDirectory.'images/'. $image->getName());
                    $this->entityManager->remove($image);
                }
                $this->entityManager->flush();
            }
        }

        return $this->render('logged/figureCreation.html.twig', array(
            'form' => $form->createView(),
            'success' => $success
        ));
    }

    /**
     * @Route("/logged/edit/{slug}", name="edit_figure")
     * @param Request $request
     * @param Figure $figure
     * @return Response
     * @throws Exception
     */
    public function editFigure(Request $request, Figure $figure) {
        $form = $this->createForm(FigureType::class, $figure);
        $form->handleRequest($request);

        if($request->isMethod('POST') && $form->isSubmitted() && $form->isValid()) {
            $figure->setUpdatedAt(new \DateTime());
            $this->entityManager->persist($figure);
            $this->entityManager->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('logged/figureEdit.html.twig', [
            'form' => $form->createView(),
            'figure' => $figure
        ]);
    }

    /**
     * @Route("/logged/delete/{slug})", name="delete_figure")
     * @param Figure $figure
     * @return RedirectResponse
     */
    public function deleteFigure(Figure $figure) {
        // on récupère les images liées à la figure
        $images = $figure->getImages();
        //on les efface du dossier upload
        foreach ($images as $image) {
            unlink($this->filesTargetDirectory.'images/'.$image->getName());
        }
        // on supprime la figure de la BDD
        $this->entityManager->remove($figure);
        $this->entityManager->flush();
        //on redirige vers la page 'home'
        return $this->redirectToRoute('home');
    }
}

src/Controller/Logged/ImageController.php
<?php

namespace App\Controller\Logged;

use App\Entity\Image;
use App\Form\ImageType;
use App\Repository\ImageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ImageController extends AbstractController
{
    private $filesTargetDirectory;

    public function __construct(string $filesTargetDirectory)
    {
        $this->filesTargetDirectory = $filesTargetDirectory;
    }

    /**
     * @Route(path="/logged/image/{id}", name="edit_image")
     * @param Image $image
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function editImage(Image $image, Request $request, EntityManagerInterface $entityManager)
    {
        $form = $this->createForm(ImageType::class, $image);
        $form->handleRequest($request);

        $success = false;

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($image);
            $entityManager->flush();

            $success = true;
            $session = $this->container->get('session');
            $session->getFlashBag()->set('success', 'Your image has been successfully updated !');

            return $this->redirect($this->generateUrl('edit_figure', [
                'id' => $image->getFigure()->getId(),
                'success' => $success
            ]));
        }

        return $this->render('logged/image/edit.html.twig', [
            'form' => $form->createView(),
            'success' => $success
        ]);
    }

    /**
     * @Route(path="/logged/image/delete/{id}", name="delete_image")
     * @param Image $image
     * @param EntityManagerInterface $entityManager
     * @param ImageRepository $imageRepository
     * @return RedirectResponse
     */
    public function deleteImage(Image $image, EntityManagerInterface $entityManager, ImageRepository $imageRepository)
    {
        unlink($this->filesTargetDirectory.'images/'. $image->getName());
        $entityManager->remove($imageRepository->find($image->getId()));
        $entityManager->flush();

        return $this->redirect($this->generateUrl('edit_figure', ['id' => $image->getFigure()->getId()]));
    }
}

src/Controller/Logged/LinkController.php
<?php

namespace App\Controller\Logged;

use App\Entity\Link;
use App\Form\LinkType;
use App\Repository\LinkRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LinkController extends AbstractController
{
    /**
     * @Route("logged/link/{id}", name="edit_link")
     * @param Link $link
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function editLink(Link $link, Request $request, EntityManagerInterface $entityManager)
    {
        $form = $this->createForm(LinkType::class, $link);
        $form->handleRequest($request);

        $success = false;

        if ($form->isSubmitted() && $form->isValid()) {
            $link->setUrl($request->request->all()['link']['link']);
            $entityManager->persist($link);
            $entityManager->flush();

            $success = true;
            $session = $this->container->get('session');
            $session->getFlashBag()->set('success', 'Your image has been successfully updated !');

            return $this->redirect($this->generateUrl('edit_figure', [
                'id' => $link->getFigure()->getId(),
                'success' => $success
            ]));
        }

        return $this->render('logged/link/edit.html.twig', [
            'form' => $form->createView(),
            'success' => $success
        ]);
    }

    /**
     * @Route("logged/link/delete/{id}", name="delete_link")
     * @param Link $link
     * @param EntityManagerInterface $entityManager
     * @param LinkRepository $linkRepository
     */
    public function deleteLink(Link $link, EntityManagerInterface $entityManager, LinkRepository $linkRepository)
    {
        $entityManager->remove($linkRepository->find($link->getId()));
        $entityManager->flush();

        return $this->redirect($this->generateUrl('edit_figure', ['id' => $link->getFigure()->getId()]));
    }

}

templates/logged/deleteFigureModal.html.twig
<button type="button" class="btn btn-danger btn-xs" title="Delete" data-toggle="modal" data-target="#imageDeleteDialog{{ figure.id }}">
    <i class="far fa-trash-alt"></i>
</button>
<div class="modal fade" id="imageDeleteDialog{{ figure.id }}" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete confirmation</h4>
            </div>
            <div class="modal-body">
                Do you really want to delete this Figure ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <a href="{{ path('delete_figure', {'slug' : figure.slug}) }}" class="btn btn-danger">Yes</a>
            </div>
        </div>
    </div>
</div>

templates/logged/figureCreation.html.twig
{% extends 'base.html.twig' %}


{% block pageContent %}
    <div class="container pageContent">
        <h1 class="pageTitle">TRICK</h1>
        {% if app.request.get('success') %}
            {% include 'messageFlash.html.twig' with {'buttonId': 'trickCreated'} %}
        {% endif %}
        {{ form_start(form) }}
        {{ form_row(form.name, {'value': ''}) }}
        {{ form_row(form.description, {'value': ''}) }}
        {{ form_row(form.figuresGroup, {'value': ''}) }}


        <div>
            <button id="add-image" class="btn btn-primary">
                <i class="fas fa-file-upload">  Add new image</i>
            </button>
            <button id="add-link" class="btn btn-primary pull-right">
                <i class="fab fa-youtube">  Add new video link</i>
            </button>
        </div>
        <div class="row">
            <div class="images col-md-6"
                 data-prototype="{{ form_widget(form.images.vars.prototype)|e }}"
                 data-index="0"
            >
                {{ form_row(form.images) }}
                <!--TODO LATER-->
                <!--<div id="preview"></div>-->
            </div>

            <div class="videoLinks col-md-6"
                 data-prototype="{{ form_widget(form.links.vars.prototype)|e }}"
                 data-index="0">
                {{ form_row(form.links) }}
            </div>
        </div>

        {{ form_errors(form) }}
        {{ form_row(form.submit) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/logged/figureEdit.html.twig
{% extends 'base.html.twig' %}

{% block pageContent %}
    <div class="container pageContent">
        {{ form_start(form) }}
        <div class="top_image">
            <div id="card_top" class="card border-dark mb-4 figure_card">
                <img class="card_image" src="{{ figure.firstImage }}" alt="image"/>
                <div class="card-footer">
                    <div class="push-right">
                        <a class="btn btn-primary" href="{{ path('edit_image' , {'id' : figure.firstImageId}) }}">
                            <i class="far fa-edit"></i>
                        </a>
                        {%  if figure.countImages() != 1  %}
                            {{ include('logged/image/deleteFirstImageModal.html.twig') }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% if app.request.get('success') %}
            {% include 'messageFlash.html.twig' with {'buttonId': 'imageUpdated'} %}
        {% endif %}
        <div class="media">
            {% for link in form.vars.data.links %}
                <div class="card border-dark mb-4 figure_card">
                    <iframe class="card_image" src="{{ link.url | replace({'watch?v=' : 'embed/'}) }}"></iframe>
                    <div class="card-footer">
                        <div class="push-right">
                            <a class="btn btn-primary" href="{{ path('edit_link' , {'id' : link.id}) }}"><i class="far fa-edit"></i></a>
                            {{ include('logged/link/deleteLinkModal.html.twig') }}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% for image in  form.vars.data.images %}
                {% if not loop.first %}
                    <div class="card border-dark mb-4 figure_card">
                        <img class="card_image" src="{{ image.getImagePath() }}" alt="image"/>
                        <div class="card-footer">
                            <div class="push-right">
                                <a class="btn btn-primary" href="{{ path('edit_image' , {'id' : image.id}) }}">
                                    <i class="far fa-edit"></i>
                                </a>
                                {{ include('logged/image/deleteImageModal.html.twig') }}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.figuresGroup) }}
        {{ form_row(form.submit) }}

        {{ form_end(form) }}
    </div>
{% endblock %}